language: php
php:
  - "5.4"
  - "5.3"
before_install:
  - composer self-update
install:
  - composer install
script:
  - ./test/run
notifications:
  irc:
    channels:
      - "chat.freenode.net##krinkle"
