name: CI
on:
  - push
  - pull_request

jobs:

  php:
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.4'
          - php: '8.0'
          - php: '8.1'
          - php: '8.2'
          - php: '8.3'
          - php: '8.4'

    name: PHP ${{ matrix.php }}

    # Includes php 8.3 and composer 2
    # https://github.com/actions/runner-images/blob/ubuntu24/20250105.1/images/ubuntu/Ubuntu2404-Readme.md#php-tools
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP ${{ matrix.php }}
      run: |
        sudo apt-add-repository ppa:ondrej/php -y
        sudo apt-get install -y -q php${{ matrix.php }} php${{ matrix.php }}-intl php${{ matrix.php }}-mbstring php${{ matrix.php }}-xml php${{ matrix.php }}-apcu php${{ matrix.php }}-curl php${{ matrix.php }}-xdebug
        php --version

    - run: composer validate
    - run: composer install
    - run: composer test
